CZ3003_SSP3_CMO/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'CZ3003_SSP3_CMO.views.home', name='home'),
    # url(r'^CZ3003_SSP3_CMO/', include('CZ3003_SSP3_CMO.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', 'myapp.views.hello', name='hello'), )

src/cmo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from cmoapp.views import *

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = CrisisReportSerializer
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)


urlpatterns = [ # pylint: disable=invalid-name
    url(r'^admin/', admin.site.urls),
    url(r'^analyst/', include('cmoapp.urls.analyst')),
    url(r'^operator/', include('cmoapp.urls.operator')),
    url(r'^chief/', include('cmoapp.urls.chief')),
    url(r'^ActionPlan/', include('cmoapp.urls.actionplan')),
    url(r'^publicmap', include('cmoapp.urls.map')),
    url(r'^account/', include('cmoapp.urls.account')),
    url('^', include('django.contrib.auth.urls')),
	#url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    # url(r'^$', login, name='login'),
    url(r'^api/', include('cmoapp.urls.api'))
]

src/cmoapp/models.py
"""All models for myapp Django application.
"""
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,ValidationError
import datetime
from datetime import timedelta

#all models have automatically add an auto-increment id unless another field is explicitly specified as primary key
#note, on_delete assigns a Function 'Callback'
#note, no fking clue in the django tutorial that says you can add a null option, only says field options are
#avaliable to all field types, but no explict example wtf
#note, if you want a FK that is null, you have to set blank=true so that validation will not be triggered

class Account(models.Model):
    TYPES = (
        ('Analyst','Analyst'),
        ('Operator', 'Operator'),
        ('Chief', 'Chief')
    )
    login = models.CharField(max_length=100)
    password = models.CharField(max_length=1024)
    type = models.CharField(max_length=20, choices=TYPES)

    class Meta:
        ordering = ['login']
    def __str__(self):
        return '{}'.format(self.login)

class CrisisType(models.Model):
    #Attributes
    name = models.CharField(max_length=50)
    def __str__(self):
        return '{}'.format(self.name)

#has nothing but a bunch of foreign keys such keys much wow
#Crisis ID
class Crisis(models.Model):
    #analyst is FK to crisis. This enables analyst to be deleted once the crisis is resolved
    #name = models.TextField()
    crisis_title = models.CharField(max_length=50,null=True)
    analyst = models.OneToOneField(Account,blank=True,null=True,limit_choices_to={'type':'Analyst'}, on_delete=models.SET_NULL)
    STATUS = (
        ('Clean-up','Clean Up'),
        ('Ongoing','Ongoing'),
        ('Resolved', 'Resolved')
    )
    status = models.CharField(max_length=20, choices=STATUS)
    external_agencies = models.TextField(null=True, blank=True)
    #class Meta:
     #   ordering = ['analyst']

    def injuries(self):
        try:
            return self.efupdate_set.latest('datetime').totalInjured
        except(EFUpdate.DoesNotExist):
            return None

    def deaths(self):
        try:
            return self.efupdate_set.latest('datetime').totalDeaths
        except(EFUpdate.DoesNotExist):
            return None

    def __str__(self):
        return 'ID: {} - assigned to: {}'.format(self.pk, self.analyst)

    def latestPlan(self):
        return self.actionplan_set.latest('id')

class CrisisReport(models.Model):
    #attributes
    description = models.TextField()
    datetime = models.DateTimeField()
    latitude = models.DecimalField(max_digits=12, decimal_places=8)
    longitude = models.DecimalField(max_digits=12, decimal_places=8)
    radius = models.IntegerField(verbose_name="Radius(Metres)", validators=[MinValueValidator(0)])
    #Relations, can have no crisis assigned for the sake of testi

    crisis = models.ForeignKey(Crisis,null=True,blank=True,on_delete=models.CASCADE)
    crisisType = models.ForeignKey(CrisisType,null=True,blank=True,on_delete=models.DO_NOTHING)

    def __str__(self):
        return 'ID: {} - {} - Crisis {} - Type: {}'.format(self.pk,self.description,self.crisis,self.crisisType)


#The response plan of the crsis.
#The deployment id is the action plan id
class ActionPlan(models.Model):
    #attributes

    #plan Number supports the CMO-PMO API as their endpoint is expecting "<<CrisisID>><<planNumber>> where "
    #where planNumber is the running number of the plan related to its crisis
    plan_number = models.IntegerField(validators=[MinValueValidator(1)], editable=False)
    description = models.TextField(null=True,blank=True)
    STATUS= (
        ('Planning','Planning'),
        ('CORequest','Requesting CO'),
        ('PMORequest','Requesting PMO'),
        ('Rejected','Rejected'),
        ('PMOApproved','Approved')
    )
    outgoing_time = models.DateTimeField(editable=False, null=True)
    status = models.CharField(max_length=20, choices=STATUS)
    resolution_time = models.DurationField()
    projected_casualties = models.IntegerField(validators=[MinValueValidator(0)])
    #Relations
    TYPES = (
        ('Combat', 'Combat'),
        ('Clean-up','Clean Up'),
        ('Resolved','Resolved')
    )
    type = models.CharField(max_length=20, choices=TYPES)
    crisis = models.ForeignKey(Crisis, on_delete= models.CASCADE)
    def abridged_description(self):
        if(len(self.description) < 140):
            return self.description
        else:
            return self.description[:140] + "..."

    def __str__(self):
        return 'ID: {} | Internal Plan Number: {} | Type: {} | Status: {} | Crisis ID: {} | Abridged Description: {} '.format(
            self.pk,
            self.plan_number,
            self.type,
            self.get_status_display(),
            self.crisis.id,
            self.abridged_description()
        )

    #Custom Model
    def clean(self, *args, **kwargs):
        # add custom validation here
        try:
            if self.status == "Planning" and ActionPlan.objects.filter(crisis=self.crisis,status="Planning").count() > 1:
                raise ValidationError("There can only be 1 Action Plan in the planning phase")
        except Crisis.DoesNotExist:
            pass    #Do nothing if there are no crisis found
        super(ActionPlan, self).clean(*args, **kwargs)

    #Method intended to be private
    def _nextPlanNumber(self):
        return self.crisis.actionplan_set.all().count() + 1

    def save(self, *args, **kwargs):
        if not self.plan_number: #only set the plan number if not set
            self.plan_number = self._nextPlanNumber()
        super().save(*args, **kwargs)  # Call the "real" save() method.

class Comment(models.Model):
    text = models.TextField()
    authors = (
        ('PMO','Prime Minister\'s Office'),
        ('CO','Chief Officer')
    )
    author = models.CharField(max_length=20, choices=authors)
    #timeCreated = models.DateTimeField(auto_now=True/auto_now_add=True) not used cause it causes the field to not be seen
    #on the DB/ admin site, it can still be referenced (hard to debug/ check)
    timeCreated = models.DateTimeField(default=timezone.now,editable=False)
    #If the CO comments, then it is rejected by CO. If PMO comments, then PMO has rejected.
    actionPlan = models.OneToOneField(ActionPlan, on_delete= models.CASCADE)

    def abridged(self):
        return self.description[:140] + "..."

    def __str__(self):
        return 'ID: {} - Author: {} - Comment: {} for Action Plan: {}'.format(self.id, self.author,self.text, self.actionPlan.id)

    def timefrom(self):
        now = datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
        difference = (now - self.timeCreated).total_seconds()
        #return hours
        if int(difference/3600) >= 23:
            return self.timeCreated.strftime('Posted on %d %b %Y, at %I:%M %p')
        elif int(difference/3600) >= 1:
            return '{} hours ago...'.format(int(difference / 3600))
        elif int(difference/60) >= 1:
            return '{} minutes ago...'.format((int(difference / 60)))
        else:
            return '{} seconds ago...'.format(int (difference))

class Force(models.Model):
    name = models.CharField(primary_key=True, max_length=200)
    #Current Utilisation can be NULL, in the event that EF cannot provide, then the field is set to NULL and Blank
    currentUtilisation = models.DecimalField(null=True,blank=True, max_digits=5, decimal_places=2)
    def __str__(self):
        return '{}'.format(self.name);
    def available(self):
        return 100-self.currentUtilisation;

#Force deployment tracks how much force to deploy for an action plan
class ForceDeployment(models.Model):
    #a force can only be deleted after all force deployments are deleted
    name = models.ForeignKey(Force, on_delete= models.PROTECT)
    recommended = models.DecimalField(max_digits=5, decimal_places=2)
    max = models.DecimalField(max_digits=5, decimal_places=2)
    actionPlan =  models.ForeignKey(ActionPlan, on_delete= models.CASCADE)

    def __str__(self):
        return 'ID: {} | Name: {} | Action Plan: {}'.format(self.pk,self.name, self.actionPlan)

    def clean(self, *args, **kwargs):
        # add custom validation here

        if self.recommended > self.max:
            raise ValidationError("Recommended amount cannot be greater than Max amount")
        super(ForceDeployment, self).clean(*args, **kwargs)

class EFUpdate(models.Model):
    #Attributes
    datetime = models.DateTimeField()
    affectedRadius = models.DecimalField(max_digits=12,decimal_places=2, verbose_name="Affected Radius")
    totalInjured = models.IntegerField(verbose_name="Total Injured")
    totalDeaths = models.IntegerField(verbose_name="Total Deaths")
    duration =  models.DurationField(null=True)
    actionPlan = models.ForeignKey(ActionPlan,null=True,on_delete = models.SET_NULL)
    #i leave this here in case the action plan can be deleted. we can thus still have a reference back to cris
    crisis = models.ForeignKey(Crisis, on_delete =  models.CASCADE)
    description = models.TextField()
    #We are removing types and adding a request
    TYPES = (
        ('Request','Request'),
        ('Notification','Notification')
    )
    type = models.CharField(choices=TYPES, max_length=40)
    def __str__(self):
        return 'ID: {}'.format(self.pk)

    def timefrom(self):
        now = datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
        difference = (now - self.datetime).total_seconds()
        #return hours
        if int(difference/3600) >= 23:
            return self.datetime.strftime('Posted on %d %b %Y, at %I:%M %p')
        elif int(difference/3600) >= 1:
            return '{} hours ago...'.format(int(difference / 3600))
        elif int(difference/60) >= 1:
            return '{} minutes ago...'.format(int(difference / 60))
        else:
            return '{} seconds ago...'.format(int (difference))

src/cmoapp/views/AccountManager.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth import logout
from cmoapp.models import Account, Crisis, CrisisReport, CrisisType, ActionPlan, Force, ForceDeployment, EFUpdate, Comment, Notifications,ForceUtilization

def index(request):
    account = Account.objects.get(login=request.user.username)
    request.session['id'] = account.id
    if account.type == 'Analyst':
        return HttpResponseRedirect('/analyst/')
    if account.type == 'Operator':
        return HttpResponseRedirect('/operator/')
    if account.type == 'Chief':
        return HttpResponseRedirect('/chief/')

    raise Http404('<h1>Invalid accounts</h1>')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login/')

src/cmoapp/views/ApiManager.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, QueryDict, JsonResponse
from django.urls import reverse
from django.utils import timezone
from cmoapp.models import Account, Crisis, CrisisReport, CrisisType, ActionPlan, Comment, Force, ForceDeployment, EFUpdate

from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions, status,generics
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from cmoapp.serializers import CrisisSerializer, CrisisReportSerializer, NineOneOneSerializer, EFSerializer, ActionPlanSerializer, CommentSerializer, AuthSerializer, PMOSerializer
from cmoapp.views import ChiefOfficerManager

import json
#Kindly help to remove unwanted modules

##CrisisReport########################################
@api_view(['POST','GET'])
@permission_classes((permissions.AllowAny,))
def crisisreport_collection(request):
    if request.method == 'GET':
        serializer = CrisisReportSerializer(CrisisReport.objects.all(), many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
    if request.method == 'POST':
        serializer = NineOneOneSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

    response_data = {}
    response_data['Status'] = 'Failed!'
    response_data['Message'] = 'CrisisReport Not Captured!'
    print(serializer.errors)
    return Response( serializer.errors, status=status.HTTP_400_BAD_REQUEST)


##Comment########################################

@api_view(['POST'])
@permission_classes((permissions.AllowAny,))
def auth_collection(request):
    if request.method == 'POST':
        serializer = AuthSerializer(data=request.data)
        response_data = {}
        if serializer.is_valid(): #and serializer2.is_valid():
            #serializer.validated_data
            #datatest = JSONRenderer().render(serializer.validated_data)
            #datatryout = json.loads(datatest)
            ap = serializer.save()
            if(serializer.data['PlanStatus'] == True):
                ChiefOfficerManager.sendDeploymentPlan(serializer.data['PlanID'])
                if(ap.type == "Resolved"):
                    ap.crisis.status = "Resolved"
                    ap.save()

            response_data['Status'] = 'Success!'
            response_data['Message'] = 'Approval Captured!'
            return Response(response_data, status=status.HTTP_200_OK)

        response_data['Status'] = 'Failed!'
        response_data['Message'] = 'Approval Not Captured!'
        print(serializer.errors)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        #return Response(response_data, status=status.HTTP_400_BAD_REQUEST)


##PMO########################################

@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def PMO_collection(request,status=None):
    print(status)
    if request.method == 'GET':
        if(status):
            crisis_list = Crisis.objects.filter(status=status)
        else:
            crisis_list = Crisis.objects.all()
        serializer = PMOSerializer(crisis_list, many=True)
        return Response(serializer.data)

    #return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


##EF########################################

@api_view(['POST'])
@permission_classes((permissions.AllowAny,))
def EF_collection(request):

    serializer = EFSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        print(serializer.errors)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    print(serializer.errors)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

src/cmoapp/views/MapManager.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from cmoapp.models import Account, Crisis, CrisisReport, CrisisType, ActionPlan, Force, ForceDeployment, EFUpdate

#Kindly help to remove unwanted modules

def loadMap(request, Location):
    latest_location_list = Location.objects.order_by('-crisis')[:5]
    context = {'latest_location_list': latest_location_list}

    try:
        forLocation = request.POST['Location']
    except(KeyError, Location.DoesNotExist):
    # Redisplay
        return render(request, 'chief/base_site.html', {
        context,
            {'error_message': "You didn't select a Location."}
        })
    else:
        return HttpResponseRedirect(reverse('cmoapp:base_site', args=(crisis.id,)))

src/cmoapp/templates/chief/ui_components/actionplan_detail.html
{% extends 'chief/base_site.html' %}
{% load custom_tags %}

{% block page_stylesheets %}
<style text="text/css">
    ul.stats-overview li
    {
        width: 22.5%
    }
</style>
{% endblock %}

{% block page_javascripts %}
 <script type="text/javascript">
     $(document).ready(function () {
        initCharts();
     });
     function initCharts(){
         {%for force in Action_Plan.forcedeployment_set.all %}
            // based on prepared DOM, initialize echarts instance
            var name = '{{force.name}}';

            var recommended = {{force.recommended}};
            var max = {{force.max}};
            var current = {{force.name.available}};
            var ctx = document.getElementById(name).getContext('2d');

            var config = {
                type:'doughnut',
                data:{
                    datasets:[
                        {
                            data:[
                                current,
                                100-current
                            ],
                            backgroundColor:[
                                "rgba(231,76,60,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBackgroundColor:[
                                "rgba(231,76,60,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBorderColor:[
                                "rgba(231,76,60,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            label: "Current Available"
                        },
                        {
                            data:[
                                max,
                                100-max
                            ],
                            backgroundColor:[
                                "rgba(52,152,219,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBackgroundColor:[
                                "rgba(52,152,219,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBorderColor:[
                                "rgba(52,152,219,.88)",
                                "rgba(0,0,0,0)"
                            ],
                            label: "Max Recommended Utilisation"
                        },
                        {
                            data:[
                                recommended,
                                100-recommended
                            ],
                            backgroundColor:[
                                "#5cb85c",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBackgroundColor:[
                                "#50a050",
                                "rgba(0,0,0,0)"
                            ],
                            hoverBorderColor:[
                                "#5cb85c",
                                "rgba(0,0,0,0)"
                            ],
                            label: "Recommended Utilisation"
                        }
                    ],
                    labels:[['Currently Available: '+current+'%', ],
                        ['Maximum Utilisation Allowed: '+max+'%',],
                        ['Recommended Utilisation: '+recommended+'%',]]
                },
                options: {
                    animation: {
                      animateScale: true,
                      animateRotate: true
                    },
                    cutoutPercentage:15,
                    tooltips: {
                      callbacks: {
                        label: function(tooltipItem, data) {
                            var dataset = data.datasets[tooltipItem.datasetIndex];
                            if(tooltipItem.index%2==1){
                                return;
                            }
                            else
                                return data.labels[tooltipItem.datasetIndex];
                        }
                      }
                    }
                }
            };
            var newChart = new Chart(ctx,config);
        {% endfor %}
     }
 </script>
{% endblock %}

{% block content %}
    <div class="right_col">
        <div class="row">
            <div class="col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h1>Plan Details</h1>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-9 col-xs-12">
                                <ul class="stats-overview">
                                    {% if Action_Plan.get_type_display == 'Combat' %}
                                    <li class="alert alert-danger">
                                        <h2 class="name">Plan Type</h2>
                                        <h4>{{ Action_Plan.get_type_display }}  <i class="fa fa-fighter-jet" aria-hidden="true"></i></h4>
                                    </li>
                                    {% else %}
                                    <li class="alert alert-info">
                                        <h2 class="name">Plan Type</h2>
                                        <h4>{{ Action_Plan.get_type_display }}  <i class="fa fa-trash" aria-hidden="true"></i></h4>
                                    </li>
                                    {% endif %}
                                    {% if Action_Plan.status == 'PMOApproved' %}
                                    <li class="alert alert-success">
                                        <h2 class="name">Approval Status</h2>
                                        <h4>{{ Action_Plan.get_status_display }}  <i class="fa fa-check-circle" aria-hidden="true"></i></h4>
                                    </li>
                                    {% elif Action_Plan.status == 'Rejected' %}
                                    <li class="alert alert-danger">
                                        <h2 class="name">Approval Status</h2>
                                        <h4>{{ Action_Plan.get_status_display }}  <i class="fa fa-times" aria-hidden="true"></i></h4>
                                    </li>
                                    {% elif Action_Plan.status == 'Planning' %}
                                    {% else %}
                                    <li class="label label-pmo">
                                        <h2 class="name">Approval Status</h2>
                                        <h4>{{ Action_Plan.get_status_display }} <i class="fa fa-spinner" aria-hidden="true"></i></h4>
                                    </li>
                                    {% endif %}
                                    <li>
                                        <h2 class="name ">  Estimated Resolution Time</h2>
                                        <h4>{% render_duration Action_Plan.resolution_time %} <i class="fa fa-clock-o"></i></h4>
                                    </li>
                                    <li>
                                        <h2 class="name">Projected Casualties</h2>
                                        <h4>{{ Action_Plan.projected_casualties }}  <i class="fa fa-heartbeat" aria-hidden="true"></i></h4>
                                    </li>
                                </ul>
                                <br>
                                <div class="form-group">
                                    <div>
                                        <label class="control-label" >Description </label>
                                    </div>
                                    <div>
                                        <textarea class="form-control" readonly>{{ Action_Plan.description|default:"None provided" }} </textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <section class="panel">
                                    <div class="x_title">
                                        <h2>Force Deployments</h2>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div id="chartsArea" class="sideBorder">
                                        {%for force in Action_Plan.forcedeployment_set.all %}
                                        <div class="x-panel">
                                            <div class="x-title">
                                                <h2 style="text-align:center;"><b>{{force.name}}</b></h2>
                                            </div>
                                            <div class="bottomBorder padding">
                                                <canvas class='x-content' id="{{force.name}}" style="height:200px;"></canvas>
                                                <h4><b>Legend</b></h4>
                                                <span class="label label-success">&nbsp&nbsp</span>
                                                <span class="name">Recommended: {{force.recommended}}%</span><br>
                                                <span class="label label-info">&nbsp&nbsp</span>
                                                <span class="name">Maximum: {{force.max}}%</span><br>
                                                <span class="label label-danger">&nbsp&nbsp</span>
                                                <span class="name">Currently Available: {{force.name.available}}%</span>

                                            </div>
                                        </div>
                                        {%endfor%}
                                    </div>
                                    <div id="main" style="height:350px;"></div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/cmoapp/templates/chief/ui_components/force_utilisation.html
{% load custom_tags %}
<div class="col-sm-12 col-xs-12">
    <div class="tile-stats row padding">
        <h2 class="center">Current Force Utilisation</h2>
         <div class="col-sm-{{sideWidth}}"></div>
        {% for force in all_force%}
        <div class="animated flipInY center col-sm-{{forceWidth}} col-xs-12">
            <div class="chart" data-percent="{{force.currentUtilisation}}">
                <div class ="percent">{{force.currentUtilisation}}%</div>
                <h2 class="center">{{force.name}}</h2>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

src/cmoapp/templates/chief/ui_components/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="/chief/" class="site_title"><i class="fa fa-spinner"></i> <span>CMO</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="/static/images/chief.png" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
      <span>Welcome,</span>
      <h2>{{name}}</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-home"></i> Home <span class="fa"></span></a>
        </li>
        <li><a><i class="fa fa-edit"></i> Crisis Information <span class="fa"></span></a>
        </li>
        <li><a><i class="fa fa-desktop"></i> Map <span class="fa"></span></a>
        </li>
        <li><a><i class="fa fa-table"></i> Deployment <span class="fa "></span></a>
        </li>
        <li><a href="/chief/historical_data/"><i class="fa fa-clock-o"></i> Historical Data <span class="fa "></span></a>
        </li>
        <li><a><i class="fa fa-clone"></i>DK PUT WHAT YET <span class="fa"></span></a>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->
</div>